### ISSUE TITLE
app.UpdateRecord is (practically) unable to use revision

### ISSUE THREAD

**Issue by arosh** [kintone-labs/go-kintone#35]
1. Since [Record.revision is a private field](https://github.com/kintone-labs/go-kintone/blob/b83b0ffcb17a11c72591215be3759a4d0b3475c4/record.go#L24), there is no way to set `revision` field for `kintone.Record` except for the use of `app.GetRecord`.
2. `kintone.Record` obtained by `app.GetRecord` contains `RECORD_NUMBER` field.
3. If `app.UpdateRecord` is called with a `kintone.Record` containing `RECORD_NUMBER`, the call will be rejected. This is because `POST /k/v1/record` will reject requests containing `RECORD_NUMBER`.

```
{code: "GAIA_UN10", id: "Dd2XiSswBhTHPPQofjOR", message: "RECORD_ID型のフィールドに値を設定することはできません。"}
```

Consequently, we cannot use `app.UpdateRecord` with a revision functionality.

## suggested change

- Delete `RECORD_NUMBER` field when `app.UpdateRecord` is called.
- Change `Record.revision` from a private field to a public field, or add new function `NewRecordWithIdAndRevision` to set revision number manually.

**Comment by josh-vo** [comment]
@arosh 
Thank you for your request, we appreciate your comments.
1/ We decided to support "NewRecordWithIdAndRevision" function, and it will be supported in the next version.
2/ After considering that the behavior is not used as many, so it won't be supported at this moment. But, we will consider supporting it in the future.
For your issue-resolving, you can manually remove "RECORD_NUMBER" when you get record data from "app.GetRecord()" before using "app.UpdateRecord()"
